import dataclasses
from dataclasses import dataclass
from typing import Optional

from utils.mongo_store_broker import mongo
from bson.objectid import ObjectId


@dataclass  # Autogenerated __init__, __eq___ and __repr__ from given fields
class Tag:
    name: str
    post_ids: list[ObjectId]
    _id: Optional[ObjectId] = dataclasses.field(default_factory=ObjectId)

    def get_id(self):  # in python _ before a field indicates that its protected so a method is used to retrieve it
        return self._id

    def __iter__(self):  # This method allows us to add support for dict() on an object
        for field in dataclasses.fields(self):
            yield field.name, getattr(self, field.name)


def find_one(_id: str | ObjectId):
    """
    Returns a tag object from db
    :param _id:
    :return:
    """
    if isinstance(_id, str):
        _id = ObjectId(_id)
    res = mongo.db.tags.find_one({"_id": _id})
    return Tag(**res)


def insert_one(obj: dict | Tag):
    """
    Inserts one tag object into the db
    :param obj:
    :return:
    """
    return mongo.db.tags.insert_one(dict(obj)).inserted_id


def update_one(_id: str | ObjectId, obj: Tag):
    """
    Updates a tag object inside the db
    :param _id:
    :param obj:
    :return:
    """
    if isinstance(_id, str):
        _id = ObjectId(_id)
    return mongo.db.tags.update_one({"_id": _id},
                                    {"$set": dict(obj)})


def delete_one(_id: str | ObjectId):
    """
    Deletes a tag object inside the db
    :param _id:
    :return:
    """
    if isinstance(_id, str):
        _id = ObjectId(_id)
    return mongo.db.tags.delete_one({"_id": _id})


def get_all():
    """
    :return: - A list of tag objects
    """
    res = mongo.db.tags.find({})
    return [Tag(**r) for r in res]
